### PR TITLE
Default search engine not set to Google in ID closes #3067

### LINKED ISSUE #3067: Default search engine not set to Google in ID
STR:
1. Set the default search engine to Google
2. Switching locale to ID 
3. Do a search using a keyword.

Expected:
The search engine should stay the same.

Actual
Default search engine for Google is missing. It becomes Yahoo.

### PR DESCRIPTION
**Pull request by cnevinc**

### CODE REVIEW

**Comment by mTwTm** [comment]
This is something I leftover and should have done it myself: Maybe we should remove the tools/search folder contents so that we don't erroneously get "google" again?

**Comment by cnevinc** [comment]
@Daisy-pliu Please help verify before shipping. Thank you!

**Comment by cnevinc** [comment]
> This is something I leftover and should have done it myself: Maybe we should remove the tools/search folder contents so that we don't erroneously get "google" again?

let's keep it as is and see the future development of Android Components.

**Comment by Daisy-pliu** [comment]
Test Result:✅
Test device : Redmi 4X (7.1.2)
Version: 1.0.8(9248) 
Webview: 71.0.3578.99
Test step:
1. change system languague

**Comment by Daisy-pliu** [comment]
Test result: ✅
Refer [Test steps/Test device](https://github.com/mozilla-tw/Rocket/issues/3067#issuecomment-454242422)
Test version: 1.0.9(9484)

**Pull request merged**
