### PR TITLE
Add Russian strings

### PR DESCRIPTION
**Pull request by dimqua**
This PR add an initial version of Russian `strings.xml` file. Please note that it's quite outdated and incomplete. But it's working. :-)

The translation has been made by @an65 user from 4pda forum. Thanks to him.

### CODE REVIEW

**Comment by dimqua** [comment]
I believe there are more than three extra strings. It seems these are not needed also:
```
<string name="abc_action_mode_done">Готово</string>
<string name="abc_activity_chooser_view_see_all">Посмотреть все</string>
<string name="abc_activitychooserview_choose_application">Выберите приложение</string>
<string name="abc_capital_off">ВЫКЛ</string>
<string name="abc_capital_on">ВКЛ</string>
<string name="abc_font_family_body_1_material">sans-serif</string>
<string name="abc_font_family_body_2_material">sans-serif-medium</string>
<string name="abc_font_family_button_material">sans-serif-medium</string>
<string name="abc_font_family_caption_material">sans-serif</string>
<string name="abc_font_family_display_1_material">sans-serif</string>
<string name="abc_font_family_display_2_material">sans-serif</string>
<string name="abc_font_family_display_3_material">sans-serif</string>
<string name="abc_font_family_display_4_material">sans-serif-light</string>
<string name="abc_font_family_headline_material">sans-serif</string>
<string name="abc_font_family_menu_material">sans-serif</string>
<string name="abc_font_family_subhead_material">sans-serif</string>
<string name="abc_font_family_title_material">sans-serif-medium</string>
<string name="abc_menu_alt_shortcut_label">Alt+</string>
<string name="abc_menu_ctrl_shortcut_label">Ctrl+</string>
<string name="abc_menu_delete_shortcut_label">delete</string>
<string name="abc_menu_enter_shortcut_label">enter</string>
<string name="abc_menu_function_shortcut_label">Функция+</string>
<string name="abc_menu_meta_shortcut_label">Meta+</string>
<string name="abc_menu_shift_shortcut_label">Shift+</string>
<string name="abc_menu_space_shortcut_label">space</string>
<string name="abc_menu_sym_shortcut_label">Sym+</string>
<string name="abc_prepend_shortcut_label">Меню+</string>
<string name="abc_search_hint">Поиск…</string>
<string name="abc_searchview_description_clear">Удалить запрос</string>
<string name="abc_searchview_description_query">Поисковый запрос</string>
<string name="abc_searchview_description_search">Поиск</string>
<string name="abc_searchview_description_submit">Отправить запрос</string>
<string name="abc_searchview_description_voice">Голосовой поиск</string>
<string name="abc_shareactionprovider_share_with">Поделиться с</string>
<string name="abc_shareactionprovider_share_with_application">Поделиться с %s</string>
<string name="abc_toolbar_collapse_description">Ошибка</string>
<string name="about_content">&lt;p&gt;%1$s&lt;br/&gt; &lt;a href=%2$s&gt;%3$s&lt;/a&gt;&lt;/p&gt;&lt;br/&gt;&lt;br/&gt; &lt;a href=%4$s&gt;%5$s&lt;/a&gt;&lt;br/&gt;&lt;br/&gt; &lt;a href=%6$s&gt;%7$s&lt;/a&gt;&lt;br/&gt;&lt;br/&gt; &lt;a href=%8$s&gt;%9$s&lt;/a&gt;&lt;br/&gt;&lt;br/&gt;</string>
```
Should I remove them also?

**Comment by dimqua** [comment]
> We have a specific l10n tool where you can do these localization

Good to know, I hope we'll get an improved version of this translation soon after more languages (including Russian) will be add to https://pontoon.mozilla.org/projects/firefox-rocket/. :-)

**Comment by mTwTm** [comment]
Thanks for the pr update, but yeah what I mean is we do the localization works on Pontoon so maybe we can't merge this from the code side. That's why I'm inviting our Pontoon project owner to comment on how we can accept these. However, seems like she hasn't seen the message yet. Let me ping her again. All of our localization work is done on Pontoon and the there's a Github repo to serve as the backing string storage: https://github.com/mozilla-l10n/zerda-android-l10n Maybe you can open an issue there as well. I'll first close this pull request although I know many hard work are already given to support this. Thank you!

**Comment by Delphine** [comment]
@dimqua Hi, and thanks for your contributions! 
We do indeed use Pontoon, our localization tool, to submit translations for Rocket. 
Could you please reach out to me via email (delphine at mozilla dot com) to discuss this more in detail? 
Looking forwards to a great localized Russian version :)

**Pull request closed without merging**
